import { StyleSheet } from "react-native";
import { color, fonts, spacing, radius, shadows } from "../../../constant";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
  },
  scrollView: {
    flex: 1,
    marginBottom: 55,
  },
  headerGradient: {
    paddingTop: spacing.sm + 2,
    paddingBottom: spacing.md,
    borderBottomLeftRadius: radius.xl,
    borderBottomRightRadius: radius.xl,
    ...shadows.md,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: fonts.bold,
    color: color.white,
  },
  headerIcon: {
    padding: spacing.sm,
  },
  profileHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md + 3,
  },
  profileImgWrapper: {
    position: "relative",
    marginRight: spacing.xl,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: radius.pill,
    borderWidth: 4,
    borderColor: color.white,
    backgroundColor: color.white,
  },
  editIconGradient: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: radius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.md,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: color.white,
    marginBottom: spacing.xs,
  },
  userEmail: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: color.white,
    marginBottom: spacing.sm,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: color.whiteAlpha20,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs,
    borderRadius: radius.lg,
    alignSelf: 'flex-start',
  },
  verifiedText: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: color.white,
    marginLeft: spacing.xs,
  },
  card: {
    backgroundColor: color.card,
    marginHorizontal: spacing.lg,
    marginTop: spacing.xl,
    padding: spacing.xl,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: color.borderLight,
    ...shadows.card,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardIconGradient: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: color.textDark,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: color.divider,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowIcon: {
    marginRight: spacing.sm + 2,
  },
  label: {
    fontSize: 15,
    fontFamily: fonts.regular,
    color: color.textMedium,
  },
  value: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    color: color.textDark,
  },
  menuItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: 'center',
    paddingVertical: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: color.divider,
  },
  menuLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuIconGradient: {
    width: 32,
    height: 32,
    borderRadius: radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  menuText: {
    fontSize: 16,
    fontFamily: fonts.medium,
    color: color.textDark,
  },
  logoutBtn: {
    marginTop: spacing.xxxl - 2,
    marginHorizontal: spacing.lg,
    padding: 1,
    borderRadius: radius.md,
  },
  logoutTouchable: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: color.transparent,
  },
  logoutText: {
    color: color.white,
    fontSize: 16,
    fontFamily: fonts.bold,
    marginLeft: spacing.sm + 2,
  },
  versionContainer: {
    alignItems: 'center',
    marginTop: spacing.xxxl - 2,
  },
  versionText: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: color.textLight,
  },

  // Guest / logged-out states
  guestHeader: {
    borderBottomLeftRadius: radius.xxl,
    borderBottomRightRadius: radius.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: spacing.xxxl + 8,
  },
  guestAvatar: {
    width: 100,
    height: 100,
    borderRadius: radius.pill,
    backgroundColor: color.whiteAlpha20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: color.whiteAlpha60,
  },
  guestTitle: {
    color: color.white,
    fontSize: 28,
    fontFamily: fonts.bold,
    marginTop: spacing.md + 3,
    letterSpacing: 1,
  },
  guestSubtitle: {
    color: color.whiteAlpha90,
    fontSize: 14,
    fontFamily: fonts.regular,
    marginTop: spacing.xs,
  },
  loginCard: {
    marginTop: -60,
    marginHorizontal: spacing.xxl,
    backgroundColor: color.card,
    borderRadius: radius.xl,
    padding: spacing.xxxl - 2,
    borderWidth: 1,
    borderColor: color.borderLight,
    ...shadows.lg,
    alignItems: 'center',
  },
  loginCardText: {
    fontSize: 18,
    color: color.textDark,
    textAlign: 'center',
    fontFamily: fonts.semiBold,
    lineHeight: 26,
    marginBottom: spacing.xxl,
  },
  loginButton: {
    paddingVertical: spacing.lg,
    borderRadius: radius.md,
    ...shadows.md,
  },
  loginButtonText: {
    color: color.white,
    fontSize: 16,
    fontFamily: fonts.bold,
    textAlign: 'center',
    letterSpacing: 1.5,
  },
  perksSection: {
    padding: spacing.xxl,
    marginTop: spacing.sm + 2,
  },
  perksTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: color.textDark,
    marginBottom: spacing.xl,
    marginLeft: spacing.xs,
  },
  perkCard: {
    width: '48%',
    backgroundColor: color.card,
    borderRadius: radius.lg,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: color.borderLight,
    alignItems: 'center',
  },
  perkIconWrap: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    backgroundColor: color.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  perkTitle: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: color.textDark,
  },
  perkDesc: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: color.textLight,
    marginTop: 2,
  },
});
