enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  Privacy="Privacy",
  EditProfile="EditProfile",

  MyOrders="MyOrders",
  OnboardingScreen = "OnboardingScreen",
  ChooseRoleScreen = "ChooseRoleScreen",
  FabricCardList = "FabricCardList",
  NonFabricCardList = "NonFabricCardList",
SearchProduct="SearchProduct",
  ViewCartScreen="ViewCartScreen",
  OrderConfirmationScreen="OrderConfirmationScreen",
  OtherCategoryData = "OtherCategoryData",
  CheckoutScreen = "CheckoutScreen",
  LoginScreen = "LoginScreen",
  PaymentHistory="PaymentHistory",
  ProductDetails = "ProductDetails",
  AddBankDetails = "AddBankDetails",
  SignUpScreen = "SignUpScreen",
  InvoiceScreen = "InvoiceScreen",
  OtpScreen = "OtpScreen",
  AccountLedger = "AccountLedger",
  BussinessDetail = "BussinessDetail",
  BankDetailsScreen = "BankDetailsScreen",
  AddressProfile = "AddressProfile",
  NotificationListScreen="NotificationListScreen",
  BottomTabs = "BottomTabs",
  CreatePassword = "CreatePassword",
  ChangePasswordScreen ="ChangePasswordScreen",
  PasswordReset = "PasswordReset",
  DashBoardScreen = "DashBoardScreen",
  ProductDetailScreen = "ProductDetailScreen",
  colorList = "colorList",
  DocumentScreen = "DocumentScreen",
  SubmittingScreen = "SubmittingScreen",
  Address = "Address",
  NotificationsSetting = "NotificationsSetting",
  OrederList = "OrderList",
  OrderDetail = "OrderDetail",
  NewAddress = "NewAddress",
  paymentMethod = "PaymentMethod",
  creditLimit = "CreditLimit",
  LimitDetail = "LimitDetail",
  AboutLimit = "AboutLimit",
  InvoiceDetail = "InvoiceDetail",
  ChatDetail = "ChatDetail",
  LoanForm = "LoanForm",
  setting = "Setting",
  language = "Language",
  personalInfo = "PersonalInfo",
  changePassword = "ChangePassword",
  card = "card",
  condition = "Conditions",
  socity = "Socity",
  AddContractWithType = "AddContractWithType",
  About = "About",
  Policy = "Policy",
  UpdateLimit = "UpdateLimit",
  DocumentView = "DocumentView"
}

export default ScreenNameEnum;
