import { Dimensions, Platform, StyleSheet } from "react-native";
import { color, fonts, radius, spacing } from "../../../constant";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  // ─── Container ───────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: color.background,
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },

  // ─── Header / Back Button ────────────────────────────────────
  headerAbsolute: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 44 : 25,
    paddingHorizontal: 18,
    paddingBottom: 10,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: color.whiteAlpha20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerActionBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: color.whiteAlpha20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    marginLeft: 10,
  },
  headerCartBadge: {
    position: "absolute",
    right: 2,
    top: 3,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: color.white,
    borderWidth: 1,
    borderColor: color.textDark,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  headerCartBadgeText: {
    fontSize: 9,
    fontFamily: fonts.bold,
    color: color.textDark,
  },

  // ─── Image Section ───────────────────────────────────────────
  imageWrapper: {
    backgroundColor: color.imagePlaceholder,
    position: "relative",
  },
  mainImage: {
    width,
    height: height * 0.66,
    resizeMode: "contain",
  },
  discountBadge: {
    position: "absolute",
    top: Platform.OS === "ios" ? 108 : 92,
    left: 18,
    backgroundColor: color.primary,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 2,
  },
  discountBadgeText: {
    color: color.white,
    fontSize: 12,
    fontFamily: fonts.bold,
    letterSpacing: 0.5,
  },
  indicatorRow: {
    position: "absolute",
    bottom: 18,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
  },
  dot: {
    height: 12,
    width: 12,
    backgroundColor: color.whiteAlpha90,
    borderRadius: 6,
    marginHorizontal: 7,
  },
  activeDot: {
    backgroundColor: color.white,
    borderWidth: 2,
    borderColor: color.borderLight,
    width: 14,
    height: 14,
    borderRadius: 7,
  },

  // ─── Thumbnail Row ───────────────────────────────────────────
  thumbnailRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: color.white,
    borderBottomWidth: 1,
    borderBottomColor: color.lightGray,
  },
  thumbnailImg: {
    width: 56,
    height: 56,
    borderRadius: 8,
    marginRight: 10,
    borderWidth: 2,
    borderColor: "transparent",
  },
  thumbnailImgActive: {
    borderColor: color.primary,
  },

  // ─── Info Card ───────────────────────────────────────────────
  infoCard: {
    backgroundColor: color.white,
    marginTop: 0,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 16,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  brandName: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: color.primary,
    letterSpacing: 1,
  },
  topSellingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: color.warningSoft,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    gap: 4,
  },
  topSellingText: {
    fontSize: 10,
    fontFamily: fonts.bold,
    color: color.warning,
  },
  productTitle: {
    fontSize: 22,
    fontFamily: fonts.regular,
    color: color.textDark,
    lineHeight: 29,
    marginBottom: 12,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: color.success,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 4,
    gap: 3,
  },
  ratingBadgeText: {
    color: color.white,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  ratingCount: {
    fontSize: 12,
    color: color.textLight,
    fontFamily: fonts.regular,
    marginLeft: 8,
  },
  divider: {
    height: 1,
    backgroundColor: color.borderLight,
    marginVertical: 14,
  },

  // ─── Price Section ───────────────────────────────────────────
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 6,
  },
  sellingPrice: {
    fontSize: 26,
    fontFamily: fonts.bold,
    color: color.primary,
    marginRight: 8,
  },
  mrp: {
    fontSize: 19,
    fontFamily: fonts.regular,
    color: color.textLight,
    textDecorationLine: "line-through",
    marginRight: 8,
  },
  offChip: {
    backgroundColor: color.primary,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: 2,
  },
  offChipText: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: color.white,
  },
  taxNote: {
    fontSize: 14,
    color: color.textLight,
    fontFamily: fonts.regular,
    marginBottom: 10,
  },
  stockTag: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  couponStrip: {
    minHeight: 45,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: color.primarySoft,
    borderRadius: 2,
    paddingLeft: 13,
    paddingRight: 88,
    marginTop: 8,
    position: "relative",
  },
  couponIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: color.lightGray,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  couponText: {
    fontSize: 16,
    color: color.primary,
    fontFamily: fonts.semiBold,
  },
  couponPrice: {
    fontFamily: fonts.bold,
  },
  couponBadge: {
    position: "absolute",
    right: 10,
    top: -18,
    width: 72,
    height: 76,
    borderRadius: 6,
    backgroundColor: color.primarySoft,
    borderWidth: 1,
    borderColor: color.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "1deg" }],
  },
  couponBadgeTop: {
    fontSize: 10,
    fontFamily: fonts.bold,
    color: color.secondary,
  },
  couponBadgeMain: {
    fontSize: 23,
    fontFamily: fonts.black,
    color: color.secondary,
    lineHeight: 27,
  },
  couponBadgeBottom: {
    fontSize: 16,
    fontFamily: fonts.black,
    color: color.secondary,
    lineHeight: 17,
  },

  // ─── Offer Strip ─────────────────────────────────────────────
  offerStrip: {
    backgroundColor: color.white,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  offerHeader: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: color.textDark,
    marginBottom: 10,
  },
  offerItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 8,
  },
  offerIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: color.warningSoft,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  offerText: {
    flex: 1,
    fontSize: 12,
    fontFamily: fonts.regular,
    color: color.textMedium,
    lineHeight: 18,
  },
  offerBold: {
    fontFamily: fonts.semiBold,
    color: color.textDark,
  },

  // ─── Delivery Section ────────────────────────────────────────
  deliveryCard: {
    backgroundColor: color.white,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  deliveryHeader: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: color.textDark,
    marginBottom: 12,
  },
  deliveryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  deliveryText: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: color.textMedium,
    flex: 1,
  },
  deliveryHighlight: {
    fontFamily: fonts.semiBold,
    color: color.textDark,
  },

  // ─── Variant Sections ────────────────────────────────────────
  variantCard: {
    backgroundColor: color.white,
    marginTop: 0,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 10,
  },
  sectionHeader: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: color.textDark,
    letterSpacing: 0.5,

    marginBottom: 12,
  },
  selectedVariantText: {
    fontFamily: fonts.regular,
    color: color.textDark,
  },
  sizeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  sizeGuide: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: color.primary,
    textDecorationLine: "underline",

  },
  variantBox: {
    minWidth: 58,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.borderLight,
    marginRight: 12,
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: color.lightGray,
  },
  variantBoxSelected: {
    borderColor: color.textDark,
    backgroundColor: color.white,
    borderWidth: 2,
  },
  variantText: {
    fontSize: 13,
    fontFamily: fonts.medium,
    color: color.textMedium,
  },
  variantTextSelected: {
    color: color.primary,
    fontFamily: fonts.bold,
  },
  colorBox: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: color.borderLight,
    marginRight: 16,
    marginBottom: 14,
    overflow: "hidden",
    padding: 4,
  },
  colorBoxSelected: {
    borderColor: color.textLight,
    borderWidth: 3,
  },
  colorLabel: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },

  // ─── Description ─────────────────────────────────────────────
  descCard: {
    backgroundColor: color.white,
    marginTop: 0,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 20,
  },
  relatedSection: {
    backgroundColor: color.white,
    paddingTop: 18,
    paddingBottom: 6,
  },
  relatedTitle: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: color.textDark,
    paddingHorizontal: 18,
    marginBottom: 14,
  },
  relatedRow: {
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  descText: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: color.textMedium,
    lineHeight: 22,
  },
  readMore: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: color.primary,
    marginTop: 6,
  },

  // ─── Bottom Bar ──────────────────────────────────────────────
  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 30 : 16,
    backgroundColor: color.white,
    borderTopWidth: 1,
    borderTopColor: color.lightGray,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  bottomIconBtn: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: color.white,
    marginRight: 10,
  },
  addToCartBtn: {
    flex: 1,
    height: 58,
    borderRadius: 18,
    overflow: "hidden",
    marginLeft: 6,
  },
  cartGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  cartBtnText: {
    color: color.white,
    fontSize: 16,
    fontFamily: fonts.bold,
    letterSpacing: 0.8,
  },

  // ─── Full Screen Modal ───────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: color.overlayDark,
  },
  modalCloseBtn: {
    position: "absolute",
    top: Platform.OS === "ios" ? 58 : 40,
    right: 20,
    zIndex: 100,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: color.whiteAlpha10,
    alignItems: "center",
    justifyContent: "center",
  },
});
