import { StyleSheet } from "react-native";
import { color, fonts, spacing, radius, shadows } from "../../../constant";
 
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md + 3,
    backgroundColor: color.background,
    borderBottomWidth: 1,
    borderBottomColor: color.borderLight,
  },
  backButton: {
    padding: spacing.sm,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: color.textDark,
  },
  headerButton: {
    padding: spacing.sm,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: spacing.xxxl - 2,
    backgroundColor: color.background,
    marginBottom: spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: color.borderLight,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: spacing.md + 3,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: radius.pill,
    borderWidth: 4,
    borderColor: color.white,
    backgroundColor: color.lightGray,
  },
  editPhotoButton: {
    position: 'absolute',
    bottom: 5,
    right: 5,
  },
  editPhotoGradient: {
    width: 40,
    height: 40,
    borderRadius: radius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.md,
  },
  photoHint: {
    fontSize: 16,
    fontFamily: fonts.semiBold,
    color: color.textDark,
    marginBottom: spacing.xs,
  },
  photoSubHint: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: color.textMedium,
  },
  formContainer: {
    backgroundColor: color.card,
    marginHorizontal: spacing.xl,
    borderRadius: radius.lg,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: color.borderLight,
    ...shadows.card,
  },
  inputContainer: {
    marginBottom: spacing.xl,
  },
  inputLabel: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    color: color.textDark,
    marginBottom: spacing.sm,
    marginLeft: spacing.xs,
  },
  inputWrapper: {
    borderWidth: 1,
    borderColor: color.borderLight,
    borderRadius: radius.md,
    backgroundColor: color.white,
    paddingHorizontal: spacing.lg,
  },
  input: {
    fontSize: 16,
    fontFamily: fonts.regular,
    color: color.textDark,
    paddingVertical: spacing.md + 2,
    height: 48,
  },
  inputError: {
    borderColor: color.error,
    backgroundColor: color.errorSoft,
  },
  errorText: {
    color: color.error,
    fontSize: 13,
    fontFamily: fonts.regular,
    marginTop: spacing.xs,
    marginLeft: spacing.xs,
  },
  textAreaWrapper: {
    position: 'relative',
    borderWidth: 1,
    borderColor: color.borderLight,
    borderRadius: radius.md,
    backgroundColor: color.white,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md + 2,
    paddingBottom: spacing.xxxl - 2,
  },
  textArea: {
    height: 100,
    paddingVertical: 0,
  },
  charCount: {
    position: 'absolute',
    bottom: spacing.sm + 2,
    right: spacing.lg,
    fontSize: 13,
    fontFamily: fonts.regular,
    color: color.textLight,
  },
  genderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: -spacing.xs,
  },
  genderOption: {
    flex: 1,
    marginHorizontal: spacing.xs,
    paddingVertical: spacing.md + 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: color.borderLight,
    backgroundColor: color.white,
    alignItems: 'center',
    position: 'relative',
  },
  genderOptionSelected: {
    borderColor: color.primary,
    backgroundColor: color.primarySoft,
  },
  genderText: {
    fontSize: 15,
    fontFamily: fonts.medium,
    color: color.textMedium,
  },
  genderTextSelected: {
    color: color.primary,
    fontFamily: fonts.semiBold,
  },
  genderCheck: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
  },
  datePicker: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: color.borderLight,
    borderRadius: radius.md,
    backgroundColor: color.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md + 2,
  },
  dateText: {
    fontSize: 16,
    fontFamily: fonts.regular,
    color: color.textDark,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: spacing.xl,
    marginTop: spacing.xxxl - 2,
    marginBottom: spacing.xl,
  },
  cancelButton: {
    flex: 1,
    marginRight: spacing.sm + 2,
    paddingVertical: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: color.white,
    borderWidth: 1.5,
    borderColor: color.borderLight,
    alignItems: 'center',
    ...shadows.sm,
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: fonts.semiBold,
    color: color.textMedium,
  },
  saveButton: {
    flex: 2,
    marginLeft: spacing.sm + 2,
    borderRadius: radius.md,
    overflow: 'hidden',
    ...shadows.md,
  },
  saveButtonGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.lg,
  },
  saveIcon: {
    marginRight: spacing.sm,
  },
  saveButtonText: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: color.white,
  },
  helpSection: {
    backgroundColor: color.card,
    marginHorizontal: spacing.xl,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.xl,
    borderWidth: 1,
    borderColor: color.borderLight,
    ...shadows.sm,
  },
  helpItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.lg + 2,
    borderBottomWidth: 1,
    borderBottomColor: color.borderLight,
  },
  helpText: {
    flex: 1,
    fontSize: 15,
    fontFamily: fonts.medium,
    color: color.textDark,
    marginLeft: spacing.md,
  },
});
