import { StyleSheet } from "react-native";
import { color } from "../../../constant";
 
export const styles = StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: color.white,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: color.white,
    borderBottomWidth: 1,
    borderBottomColor: color.lightGray,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: color.textDark,
  },
  headerButton: {
    padding: 8,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: 30,
    backgroundColor: color.white,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: color.lightGray,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: 15,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: color.white,
    backgroundColor: color.lightGray,
  },
  editPhotoButton: {
    position: 'absolute',
    bottom: 5,
    right: 5,
  },
  editPhotoGradient: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  photoHint: {
    fontSize: 16,
    fontWeight: '600',
    color: color.textDark,
    marginBottom: 5,
  },
  photoSubHint: {
    fontSize: 13,
    color: color.textMedium,
  },
  formContainer: {
    backgroundColor: color.white,
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 20,
    elevation: 4,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: color.textDark,
    marginBottom: 8,
    marginLeft: 5,
  },
  inputWrapper: {
    borderWidth: 1.5,
    borderColor: color.borderLight,
    borderRadius: 12,
    backgroundColor: '#fafafa',
    paddingHorizontal: 16,
  },
  input: {
    fontSize: 16,
    color: color.textDark,
    paddingVertical: 14,
    height: 50,
  },
  inputError: {
    borderColor: '#FF6B6B',
    backgroundColor: '#FFF5F5',
  },
  errorText: {
    color: '#FF6B6B',
    fontSize: 13,
    marginTop: 5,
    marginLeft: 5,
  },
  textAreaWrapper: {
    position: 'relative',
    borderWidth: 1.5,
    borderColor: color.borderLight,
    borderRadius: 12,
    backgroundColor: '#fafafa',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 30,
  },
  textArea: {
    height: 100,
    paddingVertical: 0,
  },
  charCount: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    fontSize: 13,
    color: color.textLight,
  },
  genderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: -5,
  },
  genderOption: {
    flex: 1,
    marginHorizontal: 5,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: color.borderLight,
    backgroundColor: '#fafafa',
    alignItems: 'center',
    position: 'relative',
  },
  genderOptionSelected: {
    borderColor: color.primary,
    backgroundColor: '#FFF5E6',
  },
  genderText: {
    fontSize: 15,
    color: color.textMedium,
    fontWeight: '500',
  },
  genderTextSelected: {
    color: color.primary,
    fontWeight: '600',
  },
  genderCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  datePicker: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: color.borderLight,
    borderRadius: 12,
    backgroundColor: '#fafafa',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dateText: {
    fontSize: 16,
    color: color.textDark,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 30,
    marginBottom: 20,
  },
  cancelButton: {
    flex: 1,
    marginRight: 10,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: color.white,
    borderWidth: 1.5,
    borderColor: color.borderLight,
    alignItems: 'center',
    elevation: 2,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: color.textMedium,
  },
  saveButton: {
    flex: 2,
    marginLeft: 10,
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: color.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  saveButtonGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
  },
  saveIcon: {
    marginRight: 8,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: color.white,
  },
  helpSection: {
    backgroundColor: color.white,
    marginHorizontal: 20,
    borderRadius: 20,
    paddingHorizontal: 20,
    elevation: 2,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  helpItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: color.lightGray,
  },
  helpText: {
    flex: 1,
    fontSize: 15,
    color: color.textDark,
    marginLeft: 12,
    fontWeight: '500',
  },

  });
