export default {
     splashbg: require('./images/bg.png'),
    logo: require('./images/logo.jpeg'),
     otp: require('./images/otp.png'),
    smsImg: require('./images/smsImg.png'),
    back: require('./images/back.png'),
    check: require('./images/check.png'),
    profile: require('./images/profile.png'),
     phone: require('./images/phone.png'),
    link: require('./images/link.png'),
    user: require('./images/user.png'),
    lock: require('./images/lock.png'),
    onboarding: require('./images/onboarding.png'),
    google: require('./images/google.png'),
    eye: require('./images/eye.png'),
    id: require('./images/id.png'),
   
    cart: require('./images/cart.png'),
    cartCircle: require('./images/cartCircle.png'),
    cartActive: require('./images/cartActive.png'),
    chat: require('./images/chat.png'),
     like: require('./images/like.png'),
    home: require('./images/home.png'),
    logoh: require('./images/logoh.png'),
   
    notification: require('./images/notification.png'),
    
    search: require('./images/search.png'),
    
    share: require('./images/share.png'),
    rate: require('./images/rate.png'),
    right: require('./images/right.png'),
    bag: require('./images/bag.png'),
    plus: require('./images/plus.png'),
     addressCircle: require('./images/addressCircle.png'),
    aboutus: require('./images/aboutus.png'),
    accressLoc: require('./images/addressLoc.png'),
    aiChat: require('./images/aiChat.png'),
    arrowdown: require('./images/arrowdown.png'),
    arrowRight: require('./images/arrowRight.png'),
    bank: require('./images/bank.png'),
    bussiness: require('./images/bussiness.png'),
    calendar: require('./images/calender.png'),
    card: require('./images/card.png'),
    card2: require('./images/card2.png'),
    cash: require('./images/cash.png'),
    changePassword: require('./images/changepassword.png'),
    coupon: require('./images/coupon.png'),
    credit: require('./images/credit.png'),
    creditlimit: require('./images/creditlimit.png'),
    costomerService: require('./images/customerService.png'),
     doc: require('./images/doc.png'),
    docCircle: require('./images/docCircle.png'),
    document: require('./images/document.png'),
    down: require('./images/down.png'),
    dummyProfile: require('./images/dummyProfile.png'),
    under: require('./images/under.png'),
    edit: require('./images/edit.png'),
    editCircle: require('./images/editCircle.png'),
    eyeoff: require('./images/eyeoff.png'),
    faq: require('./images/faq.png'),
    fast: require('./images/fast.png'),
    favorite: require('./images/favorite.png'),
    gpay: require('./images/gpay.png'),
    homeCircle: require('./images/homeCircle.png'),
    invoice: require('./images/invoice.png'),
    language: require('./images/language.png'),
     location: require('./images/location.png'),
    locationCircle: require('./images/locationCircle.png'),
    lockCircle: require('./images/lockCircle.png'),
    logout: require('./images/logout.png'),
    menu: require('./images/menu.png'),
     office: require('./images/office.png'),
    order: require('./images/order.png'),
    orderCart: require('./images/orderCart.png'),
     pe: require('./images/pe.png'),
     service: require('./images/service.png'),
      rightw: require('./images/rightW.png'),
    checkO: require('./images/checkO.png'),
    redio: require('./images/redio.png'),
    radioCheck: require('./images/radiocheck.png'),
    loginbg: require('./images/loginbg.png'),
    camera: require('./images/camera.png'),
    docImg: require('./images/docImg.png'),
     help:require('./images/help.png'),
     call:require('./images/call.png'),
    email:require('./images/email.png')

}; 